name: castit
description: Remote control app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.6+37

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  device_info_plus: ^12.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.2
  network_info_plus: ^7.0.0
  nil: ^1.1.1
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pull_to_refresh: ^2.0.0
  responsive_builder: ^0.7.1
  shared_preferences: ^2.5.4
  signalr_core:
    git: https://github.com/Wolfteam/signalr_core.git
  sprintf: ^7.0.0
  synchronized: ^3.4.0
  url_launcher: ^6.3.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  build_runner:
  freezed: ^3.2.3
  icons_launcher: ^3.0.3
  intl_utils: ^2.8.13
  json_serializable: ^6.11.2
  lint: ^2.8.0

icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
      image_path: "assets/icon/icon_ios.png"
    macos:
      enable: true
      image_path: "assets/icon/icon_macos.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

flutter_intl:
  enabled: true
